version: 1.0
app:
  maven:
    groupId: "QuickSec"
    artifactId: "QuickSec"
    version: "ee10"
    type: ear
  instances:
    min: 1
    max: 5
  endpoints: public
  resources:
    # The vCPU number for the application. If not set, it defaults to 1 vCPU. 
    # The max number of vCPU that can be requested is 14.
    cpu: 1
 # System property not needed as LDAP is updated with wildacrd cert
 # systemProperties:
 #   - name: "com.sun.jndi.ldap.object.disableEndpointIdentification"
 #    value: "true"
  # List of variables that can be referenced in the server.xml
 # variables:
  variables:
    - name: cert_defaultKeyStore
      value: abc
